module.exports = {
  ICON_AVATAR: require('../images/avatar.png'),
  ICON_AVATAR_GREEN: require('../images/avator_green.png'),
  ICON_BACK: require('../images/back.png'),
  ICON_BACK_GREEN: require('../images/back_green.png'),
  ICON_BACK_BLACK: require('../images/back_black.png'),
  ICON_CHECK_GREEN: require('../images/check_green.png'),
  ICON_COOPERATION: require('../images/icon_cooperation.png'),
  ICON_REALIZE: require('../images/icon_realize.png'),
  ICON_RESET: require('../images/reset.png'),
  ICON_RESET_GREEN: require('../images/reset.png'),
  ICON_SHOPPING_CART: require('../images/icon_shopping_cart.png'),
  ICON_SXC: require('../images/avatar_sxc.png'),
  ICON_SWITCH: require('../images/switch.png'),
  ICON_DING: require('../images/dingding.png'),
  ICON_ALIPAY: require('../images/alipay.png'),
  ICON_WECHAT: require('../images/WeChat.png'),
  ICON_DING_WHITE:require('../images/dingdingwhite.png'),
  ICON_WECHAT_WHITE:require('../images/wechatwhite.png'),
  ICON_UNSELECTED: require('../images/unselected.png'),
  ICON_SELECTED: require('../images/selected.png'),
  ICON_PWD_SHOW: require('../images/icon_pwd_show.png'),
  ICON_PWD_HIDE: require('../images/icon_pwd_hide.png'),
};
